package com.jspxcms.core.domain;

// Generated 2013-8-18 10:20:21 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsRolenodeNode generated by hbm2java
 */
@Entity
@Table(name = "cms_rolenode_node", catalog = "jspxcms2")
public class CmsRolenodeNode implements java.io.Serializable {

	private Integer rolennodeId;
	private Integer rolesiteId;
	private Integer nodeId;

	public CmsRolenodeNode() {
	}

	public CmsRolenodeNode(Integer rolennodeId, Integer rolesiteId,
			Integer nodeId) {
		this.rolennodeId = rolennodeId;
		this.rolesiteId = rolesiteId;
		this.nodeId = nodeId;
	}

	@Id
	@Column(name = "f_rolennode_id", unique = true, nullable = false)
	public Integer getRolennodeId() {
		return this.rolennodeId;
	}

	public void setRolennodeId(Integer rolennodeId) {
		this.rolennodeId = rolennodeId;
	}

	@Column(name = "f_rolesite_id", nullable = false)
	public Integer getRolesiteId() {
		return this.rolesiteId;
	}

	public void setRolesiteId(Integer rolesiteId) {
		this.rolesiteId = rolesiteId;
	}

	@Column(name = "f_node_id", nullable = false)
	public Integer getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Integer nodeId) {
		this.nodeId = nodeId;
	}

}
