package com.jspxcms.core.domain;

// Generated 2013-8-18 10:20:21 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmsWorkflowstepRole generated by hbm2java
 */
@Entity
@Table(name = "cms_workflowstep_role", catalog = "jspxcms2")
public class CmsWorkflowstepRole implements java.io.Serializable {

	private Integer wfsteproleId;
	private Integer roleId;
	private Integer workflowstepId;

	public CmsWorkflowstepRole() {
	}

	public CmsWorkflowstepRole(Integer wfsteproleId, Integer roleId,
			Integer workflowstepId) {
		this.wfsteproleId = wfsteproleId;
		this.roleId = roleId;
		this.workflowstepId = workflowstepId;
	}

	@Id
	@Column(name = "f_wfsteprole_id", unique = true, nullable = false)
	public Integer getWfsteproleId() {
		return this.wfsteproleId;
	}

	public void setWfsteproleId(Integer wfsteproleId) {
		this.wfsteproleId = wfsteproleId;
	}

	@Column(name = "f_role_id", nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "f_workflowstep_id", nullable = false)
	public Integer getWorkflowstepId() {
		return this.workflowstepId;
	}

	public void setWorkflowstepId(Integer workflowstepId) {
		this.workflowstepId = workflowstepId;
	}

}
